import { db } from "@/db";
import { clients, organizations, themes } from "@/db/schema";
import { isPremiumTier } from "@/lib/theme-fields";
import { makeLandingTemplate } from "@/lib/landing";
import { eq } from "drizzle-orm";

// ── Campaign Themes — the single resolution point (CT1) ──────────────
//
// A theme is the baked look applied to a campaign's transactional emails (CT1)
// and its landing page (CT5, generated by makeLandingTemplate). This module owns
// the EmailTheme shape, the
// in-code default that reproduces today's TalentStream look byte-for-byte, the
// precedence resolver (campaign override → brand default → gallery/default), and
// the activation-time freeze. It is a PURE READ-SIDE resolver: it renders
// whatever theme it is handed and performs no tier-gating or availability checks
// (those live in the CT2/CT3 writers).

export interface EmailTheme {
  /** All values are CSS colour strings (hex). Keys mirror the in-app brand
   *  tokens; the email kit reads `theme.palette.x` wherever it used to read `C.x`. */
  palette: {
    bg: string;
    card: string;
    primary: string;
    primaryDeep: string;
    primaryTint: string;
    accent: string;
    ink: string;
    inkSoft: string;
    inkMuted: string;
    inkFaint: string;
    border: string;
  };
  fontDisplay: string;
  fontSans: string;
  /** When set, the brand header renders this logo as an <img>; when null, the
   *  TalentStream funnel wordmark is rendered (default-theme fallback). */
  logo: { url: string; background: string; position: string } | null;
  showPoweredBy: boolean;
}

/** The snapshot frozen onto a campaign at activation (RD-1). Stored on
 *  campaigns.theme_snapshot and preferred over a live resolve for active
 *  campaigns, so editing a theme never changes a campaign already in flight. */
export interface ThemeSnapshot {
  email: EmailTheme;
  landingHtml: string | null;
  theme_id: string | null;
  frozen_at: string;
}

// Font stacks — Google fonts aren't reliably loaded across email clients, so
// these stacks fall back to widely-available system equivalents that match the
// in-app feel (editorial serif headlines, clean sans body). Kept here (rather
// than in email.ts) so DEFAULT_EMAIL_THEME is the single source of truth and
// email.ts has no module-level font constants to drift from.
export const FONT_DISPLAY =
  "'Instrument Serif', Georgia, 'Times New Roman', 'DejaVu Serif', serif";
export const FONT_SANS =
  "'Instrument Sans', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Helvetica, Arial, sans-serif";

/**
 * Reproduces today's look EXACTLY — the cobalt/vermillion palette, the font
 * stacks, the TalentStream funnel wordmark (logo: null), and the powered-by
 * footer. The palette keys rename the old module-level `C` keys in email.ts
 * (cobalt→primary, vermillion→accent, …) but the hex values are identical, so
 * the refactor is mechanical and byte-identical. This constant is the default
 * rung of the resolver: no DB hit on the common path, and being a constant it is
 * trivially provable byte-identical against the committed email snapshot.
 */
export const DEFAULT_EMAIL_THEME: EmailTheme = {
  palette: {
    bg: "#f0f3f7",
    card: "#ffffff",
    primary: "#2c5bff",
    primaryDeep: "#1a45d4",
    primaryTint: "#e8eeff",
    accent: "#05dbd6",
    ink: "#11123c",
    inkSoft: "#2f3941",
    inkMuted: "#5a6b7a",
    inkFaint: "#9fb5c4",
    border: "#d1dce6",
  },
  fontDisplay: FONT_DISPLAY,
  fontSans: FONT_SANS,
  logo: null,
  showPoweredBy: true,
};

/** The minimal client shape the resolver needs: the brand default theme id plus
 *  the brand's own logo (adopted by gallery/default themes, decision 9). */
interface ResolverClient {
  default_theme_id: string | null;
  branding_logo_url: string | null;
  logo_background: string | null;
  logo_position: string | null;
}

/** The minimal campaign shape: its (optional) own theme override + the brand. */
interface ResolverCampaign {
  theme_id: string | null;
  client: ResolverClient | null;
}

/** A gallery/default theme has no baked logo, so it adopts the rendering brand's
 *  configured logo. A logo-less brand falls back to the funnel wordmark (null). */
function brandLogo(client: ResolverClient | null): EmailTheme["logo"] {
  if (!client?.branding_logo_url) return null;
  return {
    url: client.branding_logo_url,
    background: client.logo_background ?? "light",
    position: client.logo_position ?? "top-left",
  };
}

/**
 * Resolve the effective theme for a campaign. Precedence:
 *   campaign.theme_id → brand.default_theme_id → in-code DEFAULT_EMAIL_THEME.
 * A campaign is never themeless. A theme id that no longer resolves (deleted
 * between read and resolve) silently degrades up the chain rather than throwing.
 *
 * This is the live (draft) read path. Active campaigns read theme_snapshot.email
 * instead — see the render-preference rule at every call site.
 */
export async function resolveCampaignTheme(
  campaign: ResolverCampaign
): Promise<{ email: EmailTheme }> {
  const themeId = campaign.theme_id ?? campaign.client?.default_theme_id ?? null;

  if (themeId) {
    const row = await db.query.themes.findFirst({
      where: eq(themes.id, themeId),
    });
    if (row) {
      const email: EmailTheme = {
        palette: row.palette as EmailTheme["palette"],
        fontDisplay: row.font_display,
        fontSans: row.font_sans,
        // A bespoke theme bakes its own logo; a gallery theme (logo_url null)
        // adopts the rendering brand's logo.
        logo: row.logo_url
          ? {
              url: row.logo_url,
              background: row.logo_background,
              position: row.logo_position,
            }
          : brandLogo(campaign.client),
        showPoweredBy: row.show_powered_by,
      };
      return { email };
    }
    // Row missing (deleted / set-null race) → fall through to the default rung.
  }

  // Default rung: today's look, with the brand's own logo adopted (so even a
  // Standard brand keeps its logo per the tier matrix).
  return {
    email: { ...DEFAULT_EMAIL_THEME, logo: brandLogo(campaign.client) },
  };
}

// ── Theme-assignment guards (CT2; reused by CT3) ─────────────────────
//
// The availability + tier rules that the operator (CT2) and tenant (CT3) writers
// BOTH enforce when a theme is built for, or assigned to, a brand. Factored here
// so there is a single source of truth — never two copies of "can this theme go
// on this brand?" that can drift apart.

/**
 * Is `theme` assignable to brand `brandId`? A GALLERY theme is available to every
 * brand; a CUSTOM (white-label) theme is available only to its OWN brand — never
 * another brand's or org's bespoke — and only when that brand is Premium+ (D-1).
 * `tier` is the brand's effective ORG tier (organizations.tier, the authoritative
 * copy; clients.tier is a never-written legacy mirror). Returns a tagged result
 * the caller maps to an HTTP status (404 = cross-brand bespoke hidden as
 * "not found"; 400 = the tier gate).
 */
export function assertThemeAssignable(args: {
  theme: { scope: string; client_id: string | null };
  brandId: string;
  tier: string | null | undefined;
}): { ok: true } | { ok: false; status: 400 | 404; message: string } {
  if (args.theme.scope === "custom") {
    if (args.theme.client_id !== args.brandId) {
      return {
        ok: false,
        status: 404,
        message: "Theme is not available for this brand",
      };
    }
    if (!isPremiumTier(args.tier)) {
      return {
        ok: false,
        status: 400,
        message: "A custom theme requires a Premium or Enterprise brand",
      };
    }
  }
  return { ok: true };
}

/**
 * Authoring-time integrity for a CUSTOM theme: the brand must exist, belong to
 * the supplied org (no cross-org bespoke), and its org must be Premium+. Loads
 * the brand + org tier and runs assertThemeAssignable. Returns null when OK, or a
 * `{ message, status }` the route turns into an error response.
 */
export async function guardCustomThemeBrand(
  orgId: string,
  clientId: string
): Promise<{ message: string; status: 400 | 404 } | null> {
  const brand = await db.query.clients.findFirst({
    where: eq(clients.id, clientId),
    columns: { id: true, org_id: true },
  });
  if (!brand) return { message: "Unknown client_id", status: 400 };
  if (brand.org_id !== orgId) {
    return { message: "client_id does not belong to org_id", status: 400 };
  }
  const org = await db.query.organizations.findFirst({
    where: eq(organizations.id, brand.org_id),
    columns: { tier: true },
  });
  const verdict = assertThemeAssignable({
    theme: { scope: "custom", client_id: clientId },
    brandId: clientId,
    tier: org?.tier ?? null,
  });
  return verdict.ok ? null : { message: verdict.message, status: verdict.status };
}

/**
 * CT3 tenant write-side availability gate. Loads `themeId` + the brand's org
 * tier and decides whether it may be assigned to `brand` (as a campaign override
 * or the brand default). Unlike the operator-facing `assertThemeAssignable`
 * (which 404s a sibling brand's bespoke to hide its existence), the tenant
 * writers collapse EVERY unavailability — a missing or inactive theme, a sibling
 * brand's bespoke, or a custom theme on a Standard brand — to a single `400`: a
 * tenant assigning a theme to its OWN resource is making a bad request, not
 * probing for a theme it can't see (the slice acceptance: "outside availability
 * → 400"). Returns null when the theme is assignable.
 */
export async function assertThemeAvailableForBrand(
  themeId: string,
  brand: { id: string; org_id: string }
): Promise<{ message: string; status: 400 } | null> {
  const unavailable = {
    message: "Theme is not available for this brand",
    status: 400 as const,
  };
  const theme = await db.query.themes.findFirst({
    where: eq(themes.id, themeId),
    columns: { id: true, scope: true, client_id: true, is_active: true },
  });
  // A deactivated theme is no longer pickable, even if it is a gallery theme or
  // the brand's own bespoke — treat it like a theme that does not exist.
  if (!theme || !theme.is_active) return unavailable;
  const org = await db.query.organizations.findFirst({
    where: eq(organizations.id, brand.org_id),
    columns: { tier: true },
  });
  const verdict = assertThemeAssignable({
    theme: { scope: theme.scope, client_id: theme.client_id },
    brandId: brand.id,
    tier: org?.tier ?? null,
  });
  // Collapse the operator 404 (cross-brand hide) to a tenant 400; the tier
  // message is kept verbatim because it is genuinely actionable (upgrade to
  // Premium), unlike the deliberately-opaque cross-brand case.
  return verdict.ok ? null : { message: verdict.message, status: 400 };
}

/**
 * The effective landing-page paste override for a campaign, or null. An override
 * is honoured ONLY for Premium+ brands (a Standard brand never gets one) and only
 * when it is non-blank — a blank "" must fall through to the generated landing,
 * never render an empty page. Single source of truth for both render and freeze.
 */
function landingOverride(
  tier: string | null,
  htmlTemplate: string | null
): string | null {
  if (!isPremiumTier(tier)) return null;
  return htmlTemplate && htmlTemplate.trim() ? htmlTemplate : null;
}

/**
 * Resolve the landing HTML the public careers page should render for a campaign
 * (CT5). A campaign is NEVER landing-less: the themed landing is generated from
 * the resolved palette via makeLandingTemplate, and the per-campaign paste
 * (html_template) is only an optional Premium-tier override.
 *
 * - Active campaigns read the frozen snapshot: a Premium override frozen at
 *   activation wins; otherwise the themed landing is regenerated from the FROZEN
 *   palette (snapshot.email), so editing a theme never disturbs an in-flight
 *   campaign (RD-1) yet active campaigns still pick up the shared layout.
 * - Drafts (no snapshot) resolve live: the html_template override is honoured
 *   only for Premium+ brands; everyone else gets the theme-generated landing.
 */
export async function resolveEffectiveLanding(
  campaign: ResolverCampaign & {
    html_template: string | null;
    theme_snapshot: ThemeSnapshot | null;
    tier: string | null;
  }
): Promise<string> {
  if (campaign.theme_snapshot) {
    const frozen = campaign.theme_snapshot.landingHtml;
    return frozen && frozen.trim()
      ? frozen
      : makeLandingTemplate(campaign.theme_snapshot.email);
  }
  const { email } = await resolveCampaignTheme(campaign);
  return (
    landingOverride(campaign.tier, campaign.html_template) ??
    makeLandingTemplate(email)
  );
}

/**
 * Freeze the resolved look at activation (RD-1). Captures the live resolver's
 * email theme; the landing is NOT baked (it regenerates from `email` at render),
 * so the snapshot's landingHtml stores ONLY a Premium-tier paste override (or
 * null). A Standard brand can never freeze an override — the gate is structural.
 * Re-frozen on every into-active transition; never re-frozen by an edit to an
 * already-active campaign.
 */
export async function freezeCampaignTheme(
  campaign: ResolverCampaign & {
    html_template: string | null;
    tier: string | null;
  }
): Promise<ThemeSnapshot> {
  const resolved = await resolveCampaignTheme(campaign);
  return {
    email: resolved.email,
    landingHtml: landingOverride(campaign.tier, campaign.html_template),
    theme_id: campaign.theme_id ?? null,
    frozen_at: new Date().toISOString(),
  };
}
