services:
  postgres:
    image: postgres:16-alpine
    container_name: talentstream-postgres
    environment:
      POSTGRES_USER: talentstream
      POSTGRES_PASSWORD: talentstream_dev
      POSTGRES_DB: interview_insider
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: talentstream-azurite
    command: "azurite --blobHost 0.0.0.0 --queueHost 0.0.0.0 --tableHost 0.0.0.0 --skipApiVersionCheck -l /data"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite-data:/data

volumes:
  pgdata:
  azurite-data:
