import { db } from "@/db";
import { campaigns, candidates, clients } from "@/db/schema";
import { error, getApiTenant, success } from "@/lib/api";
import { orgScope } from "@/lib/tenant";
import { and, desc, eq } from "drizzle-orm";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  // S4: org-scope the campaign read (keeps the client relation) → cross-org id
  // 404s before any candidate PII is assembled. orgScope on the candidate
  // queries is defence-in-depth.
  const { ctx, response } = await getApiTenant();
  if (response) return response;

  try {
    const { id } = await params;

    const campaign = await db.query.campaigns.findFirst({
      where: and(eq(campaigns.id, id), orgScope(campaigns, ctx)),
      with: { client: true },
    });

    if (!campaign) return error("Campaign not found", 404);

    // All candidates for summary counts
    const allCandidates = await db
      .select({ status: candidates.status })
      .from(candidates)
      .where(and(eq(candidates.campaign_id, id), orgScope(candidates, ctx)));

    const totalApplied = allCandidates.length;
    const totalPassed = allCandidates.filter((c) =>
      ["gating_passed", "scoring", "scored", "follow_up", "shortlisted"].includes(c.status)
    ).length;
    const totalScored = allCandidates.filter((c) =>
      ["scored", "follow_up", "shortlisted"].includes(c.status)
    ).length;
    const totalShortlisted = allCandidates.filter((c) => c.status === "shortlisted").length;

    // Shortlisted candidates with full details
    const shortlisted = await db
      .select()
      .from(candidates)
      .where(and(eq(candidates.campaign_id, id), eq(candidates.status, "shortlisted"), orgScope(candidates, ctx)))
      .orderBy(desc(candidates.ai_score));

    const report = {
      campaign: {
        role_title: campaign.role_title,
        department: campaign.department,
        location: campaign.location,
        client_name: campaign.client?.name ?? null,
        campaign_start: campaign.campaign_start,
        campaign_end: campaign.campaign_end,
      },
      summary: {
        total_applied: totalApplied,
        total_passed: totalPassed,
        total_scored: totalScored,
        total_shortlisted: totalShortlisted,
      },
      candidates: shortlisted.map((c) => {
        const dims = (c.ai_dimensions ?? {}) as Record<string, number>;

        // Try to extract structured info from rationale
        let recommendation: string | null = null;
        try {
          // The recommendation might be stored in scoring logs, but we approximate from score
          if (c.ai_score && c.ai_score >= 8.5) recommendation = "strong_recommend";
          else if (c.ai_score && c.ai_score >= 7.5) recommendation = "recommend";
          else if (c.ai_score && c.ai_score >= 6) recommendation = "recommend_with_caveats";
          else if (c.ai_score && c.ai_score >= 5) recommendation = "borderline";
          else recommendation = "reject";
        } catch {
          // ignore
        }

        return {
          name: c.name,
          score: c.ai_score,
          confidence: c.ai_confidence,
          recommendation,
          dimensions: dims,
          rationale: c.ai_rationale,
          shortlist_notes: c.shortlist_notes,
        };
      }),
      generated_at: new Date().toISOString(),
      disclaimer:
        "This report was generated by TalentStream using AI-assisted candidate assessment. " +
        "Scores and recommendations are intended as decision-support tools and should be " +
        "considered alongside human judgement. All candidate data is processed in compliance " +
        "with POPIA. Full scoring rationale and audit logs are available upon request.",
    };

    return success(report);
  } catch (err) {
    console.error("GET /api/admin/campaigns/[id]/report error:", err);
    return error("Internal server error", 500);
  }
}
